export const FILTER_BY_CATEGORIES = 'FILTER_BY_CATEGORIES';
export const FILTER_BY_RATING = 'FILTER_BY_RATING';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const SORT_BY = 'SORT_BY';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';